# app/email_client.py

import os
import logging
from dotenv import load_dotenv
from sendgrid import SendGridAPIClient
from sendgrid.helpers.mail import Mail
from datetime import datetime, timezone, timedelta

load_dotenv()
logger = logging.getLogger(__name__)


def send_security_email(recipient: str, scan_result: dict) -> bool:
    """
    Sends a formatted security alert email matching the Slack message.
    """

    api_key = os.getenv("SENDGRID_API_KEY")
    from_email = os.getenv("FROM_EMAIL")

    if not api_key or not from_email:
        logger.error("❌ SendGrid not configured (missing env vars)")
        return False

    repo = scan_result.get("repo", "Unknown Repo")
    branch = scan_result.get("branch", "Unknown Branch")
    author = scan_result.get("author", "Unknown Author")
    severity = scan_result.get("severity", "unknown").upper()
    action = scan_result.get("action", "UNKNOWN")
    incident = scan_result.get("incident", "Security Issue")
    summary = scan_result.get("summary_en", "No summary available.")
    issues = scan_result.get("issues_summary", "No issues listed.")
    fix = scan_result.get("fix", "Refer to security guidelines.")
    pr_url = scan_result.get("pr_url", "#")
    now_utc = datetime.now(timezone.utc)
    now_ist = now_utc + timedelta(hours=5, minutes=30)

    time = (
        f"{now_ist.strftime('%Y-%m-%d')} | "
        f"{now_ist.strftime('%H:%M:%S IST')}"
    )
        
    subject = f"🚨 [ATF Sentinel] {action} — {repo}"

    # ---------- TEXT VERSION ----------
    text_content = f"""
🚨 SECURITY ALERT — ATF Sentinel

Repository : {repo}
Branch     : {branch}
Author     : {author}
Severity   : {severity}
Action     : {action}
Time       : {time}

Incident:
{incident}

Summary:
{summary}

Issues:
{issues}

Recommended Fix:
{fix}

Pull Request:
{pr_url}

— ATF Sentinel
"""

    # ---------- HTML VERSION ----------
    html_content = f"""
<html>
<body style="font-family: Arial, sans-serif; color: #333;">
  <h2 style="color:#d32f2f;">🚨 Security Alert — ATF Sentinel</h2>

  <table cellpadding="6">
    <tr><td><b>Repository:</b></td><td>{repo}</td></tr>
    <tr><td><b>Branch:</b></td><td>{branch}</td></tr>
    <tr><td><b>Author:</b></td><td>{author}</td></tr>
    <tr><td><b>Severity:</b></td><td style="color:red;"><b>{severity}</b></td></tr>
    <tr><td><b>Action:</b></td><td><b>{action}</b></td></tr>
    <tr><td><b>Time:</b></td><td>{time}</td></tr>
  </table>

  <hr>

  <h3>Incident</h3>
  <p>{incident}</p>

  <h3>Summary</h3>
  <p>{summary}</p>

  <h3>Detected Issues</h3>
  <pre style="background:#f5f5f5;padding:10px;border-radius:5px;">{issues}</pre>

  <h3>Recommended Fix</h3>
  <p>{fix}</p>

  <p>
    🔗 <a href="{pr_url}" target="_blank">View Pull Request</a>
  </p>

  <hr>
  <p style="font-size:12px;color:#777;">
    This is an automated security alert generated by ATF Sentinel.
  </p>
</body>
</html>
"""

    message = Mail(
        from_email=from_email,
        to_emails=recipient,
        subject=subject,
        plain_text_content=text_content,
        html_content=html_content,
    )

    try:
        sg = SendGridAPIClient(api_key)
        response = sg.send(message)
        logger.info(f"📧 Email sent to {recipient} (status {response.status_code})")
        return True
    except Exception as e:
        logger.error(f"❌ Failed to send email: {e}")
        return False
